:sources: 
  BlobTest: 
    :poll_interval: 0
  BlobTest_s: 
    :poll_interval: 0
  Image: 
    :poll_interval: 0
  Metadata: 
    :poll_interval: 0
 
:test: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
:production: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
:development: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
